const data = {
    'Kurnool': {
      'Adoni': [''],
      'Dhone': [''],
      'Kurnool': [''],
      'Pattikonda': [''],

    },
    'Nandyal': {
      'Atmakur': ['Aamalapuram','Bapanathapuram','Indireswaram','Karivena','Krishnapuram','Kurukunda','Mustepalli','Nallakalva','Pinnapuram','Siddapuram','Siddepalli','Sripathirao peta','V. Ramapuram'],
      'Bandiatmakur': ['B.Atmakur','B.Kodur','Bhojanam','ChinnaDevalapuram','Eernapadu','G.C.Palem','G.Linagapuram','Kadamalakalva','Kakanuru','Narayanapuram','Parmaturu','Parnapali','Peddadevalapuram','Ramapuram','Santhajuturu','Singavaram','Somayajulapalli','YerraGuntla'],
      'Nandyal': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Sirivella': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Rudravaram': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Allagadda': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Chagalamarri': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Uyyalawada': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Dornipadu': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Gospadu': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Koilkuntla': ['Amadala','Bheemunipadu','soudherdinna','Velagaturu','	Revanuru','Gulladurthi','Gunjapadu','	Joladerasi','	Pottipadu','Lingala','Koilakuntla','Kampamalla','Kalugotla','Pedda kopperla', 'Chinna Kopperla', 'Bijinivemula'],
      'Banaganapalli': ['Appalapuram','BANAGANAPALLI','Beravulu','Cherupalli','I.Kothapeta','Krishna giri','Kypa','Meerpuram','MITTEPALLI','Nandavaram','Nandivargam','Palukur','Pasupula','Pathapadu','Ramateertham','Taguturu','Thamadapalli','Thimapuram','Venkatapuram','YAGANTIPALLI','Yanakandla','Yerragudi'],
      'Kolimigundla': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Owk': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Sanjamala': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Mahanandi': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Panyam': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Gadivemula': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Srisailam': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Peapully': ['Hyderabad', 'Warangal', 'Karimnagar'],
      'Dhone': ['Avuladoddi','Ch.Malkapuram','Chanugondla','Devarabanda','Dharmavaram','Dorapalli','Gosanipalli','Gummakonda','Jagadurthy','Kamaganikuntla','Kamalapuram','Kannapukunta','Kocheruvu','Kothaburuju','Kothakota','Kotrai','Mallempalli','U.Kothapalli','Udumulapadu','Ungaranigundla','Vekatanayunipalli','Venkatapuram','Yapadinne','Yarraguntla','Yeddupenta'],
      'Velgodu': ['Abdullahpuram','Boyarevula','Guntakandala','Madavaram','Mothkur','Regadagudur','Velgode','Velpanur'],
      'Pamulapadu': ['Banakacherla','Bhanumukkala','Chelimilla','Erragudur','Iskala','Jutur','Lingala','Maddur','Mittakandala','Pamulapadu','Rudravaram','Vanala','Vempenta'],
      'Pagidyala': ['K.Muchumarri','Lakshmapuram','M.Ganapuram','Nehrunagar','P.Muchumarri','Pagidyala','Sankirenipalli'],
      'Betamcherla': ['Ambapuram','Bethemcherla','Bugganipalli','Bukkapuram','Cement nagar','Emboy','Gorlagutta','Gorumankonda','Gutupalli','H.Kottala','K.K.Kottala','Kolumulapalli','M. Pendekal','Muddavaram','R. Kothapalli','R.S. Rangapuram','Rahimanpuram','Sankalapuram','Seetharamapuram','Thavisikonda'],
      'JupaduBunglow': ['80-Bannur','Bhaskarapuram','Jupadubunglow','Mandlem','P. Ghanapuram','P. Lingapuram','Paramanchala','Tartoor','Tatipadu','Thangadancha','Tharigopula','Thudicherla'],
      'Kothapalli': ['Dudyala','G. Veerapuram','Gokavaram','Gummadapuram','Guvvalakuntla','Kokkarancha','Kothapalli','Musalimadugu','Nandikunta','Sivapuram','Yedurupadu','Yerramatam'],
      'Midthur': ['49-Bannur','Alaganur','Byrapuram','Cherukucharla','Chintalapalli','Chowtkur','Devanur','Jalakanur','Kadumur','Masapeta','Midthur','Nagaluty','Paipalem','Peerusabpeta','Rollapadu','Sunkesula','Talamudipi','Thimmapuram','Veepanagandla'],
      'Nandikotkur': ['10-Bollavaram','Allur','Bramhanakotkur','Damagatla','K.Bijinivemula','Kollabavapuram','Konetamapalli','Konidela','Malyala','Nagatur','Satanikota','Vaddeman'],
      
    },
    'Anantapur': {
        'Pamidi': ['Anumpalli','Debbasanipalli','Devarapalli','Eddulapalli','G.Kottala','Gajarampalli','Kandlapalli','Katrimala','Kattakindapalli','Khadeerpeta','Neeluru','Palyam','Palyam Thanda','Ramagiri','Ramarajupalli','Sorakayalapeta','Vankarajukalva','Yedururu','RAMAGIRI YEGUVA THANDA'],
        'Guntakal': ['PULIGUTTAPALLI PEDDA THANDA','Ayyavaripalli','Chintalampalli','Dancherla','Donimukkala','Dosaludiki','G.Kottala','Gundala','Gundala thanda','Gurrabadu','Imampuram','Kadiripalli','Kasapuram','Konganapalli','Molakalapenta','N.Thimmapuram','Nagasamudram','Nakkanadoddi','Nalladasaripalli','Nelagonda','Obulapuram','P.K.Cheruvu','Pulaguttapalli','Venkatampalli','Y.T.Cheruvu'],
        'Garladinne': ['Budedu','Garladinne','Illuru','Kalluru','Kamalapuram','Kanampalli','Kesavapuram','Koppalakonda','Kotanka','Krishnapuram','M.P.R.Dam','Marthudu','Mukundapuram','Muntimadugu','Penakacherla','Sirivaram','Thimmampeta','Yerraguntla'],
        'Peddavadaguru': ['A.Thimmapuram','Appecherla','Bheemunipalli','Burnakunta','Chinnavaduguru','Chintalachervu','Chitrachedu','Chitturu','Demmagudi','Gooty Anantapuram','Gooty Venkatampalli','Kasepalli','Kondlaguduru','Kristipadu','Lakshumpalli','Mallenipalli','Medimaakulapalli','Midthuru','Muppalagooty','P.Kottalapalli','Peddavaduguru','Penakalapadu','Rampuram','Ravuludiki','Virupaapuram'],
        'Uravakonda': ['Lathavaram Thanda','Amidyala','Budagavi','Chinnamustoor','Indravathi','Lathavaram','Mopidi','Neremetla','Nimbagal','Pedda Kowkuntla','Peddamustoor','Raketla','Rayampalli','Renimakulapalli','Shaiksanipalli','Uravakonda','Veligonda','Vyasapuram'],
        'Vajrakarur': ['NNP THANDA','Chabala','Chayapuram','Chinnahothur','Dharmapuri','Gadehothuru','Gangikunta','Gulyapalyam','J.Rampuram','Kadamalakunta','Kamalapadu','Konakondla','P.C.Pyapili','Ragulapadu','Tatrakal','V.Pandikunta','Vajrakaruru','Venkatampalli','Rupenaik Thanda'],
        'Anantapur Rural': ['Papampeta','A.Narayanapuram','Akkampalli','Akuthotapalli','Alamuru','Anantapur(R)','Chinnampalli','Chiyyedu','Itikalapalle','Kakkalapalli','KakkalapalliColony','Kamarupalli','Kandukur','Katiganikalva','Kattakindapalli','Kodimi','Kurugunta','Mannila','Narasanayuni Kunta','Pulakunta','Rachanapalle','Rajiv Colony','Rudrampeta','Somaladoddi','Thaticherla','Upparapalli'],
        'Atmakur': ['Atmakur(N)','B.Yaleru','Gorudindla','Madigubba','Muttala','P.Siddarampuram','P.Yaleru','Pampanuru','Rangampeta','Sanapa','Singampalli','Talupuru','Thopudurti','Vaddupalli','Vepacherla','SINGAMPALLI THANDA','VEPACHERLA DIGUVA THANDA'],
        'B.K.Samudram': ['B.K.Samudram (N)','B.Kothapalli','Bommalatapalli','Chadulla','Chennampalli','Danduvaripalli','Dayyalakuntapalli','Govindampalli','Janthuluru','K.K.Agraharam','Korrapadu','Neelampalli','Pasaluru','Podaralla','R.Kotturu','Reddipalli','Sinddarampuram','Vadiyampeta','Venkatapuram',],
        'Garladdine': ['Budedu','Garladinne','Illuru','Kalluru','Kamalapuram','Kanampalli','Kesavapuram','Koppalakonda','Kotanka','Krishnapuram','M.P.R.Dam','Marthudu','Mukundapuram','Muntimadugu','Penakacherla','Sirivaram','Thimmampeta','Yerraguntla'],
        'Putluru': ['A Kondapuram','Arakatavemula','Balapuram','Chalavemulapalli','Cherlopalli','Doseledu','Gandlapadu','Garuguchintalapalli','Jangamreddypeta','Kadavakallu','Kandikapula','Komatikuntla','Kondepalli','Kummanamala','Maddepalli','Madugupalli','Putluru','Rangarajukunta','S.Guduru','S.Vengannapalli','Surepalli','Takkallapali','Yellutla'],
        'Peddapappur': ['Amalladinne','C.Chikkepalli','Chagallu','Cheemalavagupalli','Chinnayakkaluru','Devanuppalapadu','Dharmapuram','Garladinne','Jutur','Kummetha','Muchukota','Namanankapalli','Narasapuram','P.Cherlopalli','Pasalur','Peddapappur','Peddayakkaluru','Somanapalli','Tabjula','Varadayapalli'],
        'Rapthadu': ['Bhoginepalli','Bommeparthi','Bukkacherla','G.Kothapalli','Gandlaparthi','Gollapalli','Gondireddipalli','Hampapuram','M.B.Palli','M.Cherlopalli','Maruru','Palacherla','Prasannayapalli','Pullalarevu','Rapthadu','Yerraguntla'],
        'Singanamala': ['NAGULAGUDDAM THANDA','Akuledu','Chakrayapeta','Gummepalli','Joolakaluva','Kallumadi','Korivipalli','Lolur','Matlagondi','W.Narsapuram','Nayanavaripalli','Nidanawada','Peravali','Rachepalli','Salakamcheruvu','Singanamala','Sodanapalle','Tarimela','Ullikallu'],
        'Tadipatri': ['Alur','Bhogasamudram','Bodayapalli','Bondaladinne','Bramhanapalli','Challavaripalli','Chinnapolamada','Chukkalur','Diguvapalli','Gangadevapalli','Gannevaripalli','Hussainapuram','Igudur','Kavetisamudram','Komali','Kondepalli','Peddapolamada','Ravivenkatempalli','Sajjaladinne','Terannapalli','Urichinthala','Vanganur','Veerapuram','Velamakur','Venkata Reddi palli','Yerraguntapalli'],
        'Yadiki': ['23/2Nittur','C.Lakshumpalli','Chandna','Gudipadu','Kamalapadu','Konuppalapadu','N.Chikkepalli','Nagarur','P.Vengannapalli','Puppala','Rayalacheruvu','Thutrallapalli','Vemulapadu','Yadiki'],
        'Yellanur': ['85 Nitturu','Boppepalli','Bukkapuram','Chintakayamanda','Chlamakuru','Dantalapalli','Goddumarri','Jangampalli','Kalluru','Kuchivaripalli','Mallagundla','Medikurthy','Neerajampalli','Pathapali','Peddamallepalli','S.Thirumalapuram','Singavaram','Veemulapalli','Venkatampalli','Vennapusapalli','Yellanur'],
        'Narpala': ['B.Pappur','Bandlapalli','Bondalawada','Chamaluru','Duggumarri','Gaddamnagepalli','Ganganapalli','Gugudu','Gunjepalli','H.Sodanapalli','Kesepalli','Nadimidoddi','Narpala(N)','Nayananapalli','Rangapuram','Siddaracherla','Venkatampalli'],
        'Kudair': ['Aravakuru','Cholasamudram','Gutukuru','Ipperu','Jallipalli','Kalagalla','Kammuru','Korrakodu','Kuderu','Marutla','uddalapuram','P.Narayanapuram','Thimmapuram','Udiripikonda'],
        'Gooty': ['Abbedoddi','Basinepalli','Bethapalli','Brahmanapalli','Cherlopalli','Dharmapuram','Issurallapalli','Jakkalacheruvu','Karidikonda','Kojjepalli','Kothapeta','Lachanapalli','Mamadur','Peddoddi','Rajapuram','T. Kothapalli','Thondapadu','Thurakapalli','Ubicherla','Utakallu','Vannedoddi','Yengannapalli','Yerragudi','BASINEPALLI THANDA'],
        'Vidapanakal': ['Chekalaguriki','Donekallu','Gadekallu','Hanchanahallu','Havaligi','Janardhanapalli','Kadadharabench','Karakamukkala','Kottalapalli','Malapuram','Palthuru','Poliki','R.Kottala','Undabanda','V.Kothakota','Velpumadugu','Vidapanakallu'],
        'Beluguppa': ['YALAGALAVANKA THANDA','Ankampalli','Avulenna','B. Ramasagaram','Beluguppa','Duddekunta','Gangavaram','Hanimireddypalli','Jeedipalli','Kaluvapalli','N. Gundlapalli','Nakkalapalli','Narasapuram','Raminepalli','Seeripi','Sreerangapuram','Thagguparthy','Virupapalli','Yerragudi'],
        'Bommanahal': ['Banudur','Bollanaguddam','Bommanahal','D.Honnur','Elanji','Gonehal','Govindawada','Haresamudram','Kalluhola','Kolaganahalli','Kuruvalli','Lingadahal','Nemakal','Siddarampuram','Singanahalli','Sreedharagatta','Uddehal','Unthakal','Upparaha'],
        'Bramhasamudram': ['Bhirasamudram','Bhyravanithippa','Bommaganipalli','Brahmasamudram','Gundiganipalli','Kanepalli','Mupullakuntta','Nagireddipalli','Palavenkatapuram','Pillapalli','Royallappadoddi','Santhekondapuram','Theetakal','Vepulaparthy','West Kodipalli','Yerradikerra'],
        'D.Hirehal': ['Cherlopalli','D.Hirehal','Dodagatta','Hullikallu','Jajarakallu','Kadaluru','Kudluru','M.Hanumapuram','Madenahalli','Malapanagudi','Mallikethi','Muradi','Nagalapuram','Obulapuram','Pulakurthi','Somalapuram'],
        'Gummagatta': ['75 veerapuram','Belodu','Bhupasamudram','Galagala','Gollapalli','Gonabavi','Gummagatta','K p doddi','Kalugodu','Marempalli','Netrapalli','Pulakunta','Rangasamudram','Sirige doddi','Tallakere'],
        'Kalyandurg': ['Battuvanipalli','Borampalli','Byadrahalli','Chapiri','Durdakunta','East Kodipalli','Garudapuram','Golla','Hulikal','Kotturu','M.Kondapuram','Maddinayanapalli','Manirevu','Narayanapuram','Palavai','PTR Palli Thanda','Thimmasamudram'],
        'Kambaduru': ['Chennampalli','Gollapalli','Kambadur','Karthanaparthi','Kurakulapalli','Marimekalapalli','Mulakanuru','Nootimadugu','Palluru','Ralla Anantapuram','Rampuram','Thimmapuram'],
        'Kanekal': ['43-Udegolam','Benikal','Bidurukontham','Bramhasamudram','Ganigera','Garudachedu','Gopulapuram','Hanakanahal','Hullikera','Jakkalavadiki','Kalekurthy','Kanekal','Malyam','N.Hanumapuram','Rachumarri','Sollapuram','Thumbiganur','Yerragunta'],
        'Kundupi': ['Appilepalli','Basapuram','Bestharapalli','Jambugumpala','Kariganipalli','Kundurpi','Mahanthapuram','Malayanur','Nijavalli','Tenagallu','Thumukunta','Yanumaladoddi','Yarrakunta'],
        'Rayadurgam': ['74-Udegolam','Avuladatla','Baginayakanahalli','Bondanakal','Chadam','Chadam Gollaladoddi','D.Kondapuram','Gramdatla','Junjurampalli','Kenchanapalli','Konthanapalli','Mallapuram','Mechiri','Nagireddypalli','Pallepalli','Rekulakunta','T.Veerapuram','Vadrahannurur','Veparala'],
        'Setturu': ['Aumpalli','Ayyagarlapalli','Bache Halli','Cherlopalli','Chinnampalli','Chintharlapalli','Idukal','Kanukur','Khyrevu','Lakshmampalli','Makodiki','Mulakaledu','Perugupalyam','Settur','Thippanapalli','Yatakal'],
      },
      'Kadapa': {
        'Kamalapuram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Jamalamadugu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Badvel': ['Manhattan', 'Brooklyn', 'Queens'],
        'Proddatur': ['Manhattan', 'Brooklyn', 'Queens'],
        'Pendlimarri': ['Manhattan', 'Brooklyn', 'Queens'],
        'Chennur': ['Manhattan', 'Brooklyn', 'Queens'],
        'kondapuram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Lingala': ['Manhattan', 'Brooklyn', 'Queens'],
        'Rajupalem': ['Manhattan', 'Brooklyn', 'Queens'],
        'Duvvur': ['Manhattan', 'Brooklyn', 'Queens'],
        'Muddanur': ['Manhattan', 'Brooklyn', 'Queens'],
        'Peddamudium': ['Manhattan', 'Brooklyn', 'Queens'],
        'Mylavaram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Simhadripuram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Chakrayapet': ['Manhattan', 'Brooklyn', 'Queens'],
        'B.Kodur': ['Manhattan', 'Brooklyn', 'Queens'],
        'Siddavatam': ['Manhattan', 'Brooklyn', 'Queens'],
        'Chapad': ['Manhattan', 'Brooklyn', 'Queens'],
      },
      'YSR district': {
        'New York': ['Manhattan', 'Brooklyn', 'Queens'],
        'California': ['Los Angeles', 'San Francisco', 'San Diego'],
      },
      'East Godavari': {
        'Amalapuram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Korukonda': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Thallarevu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kajuluru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kapileswarapuram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Rajanagaram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Biccavolu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Mandapeta': ['Manhattan', 'Brooklyn', 'Queens'],
      },
      'West Godavari': {
        'Narasapuram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Achanta': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Poduru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Penugonda': ['Manhattan', 'Brooklyn', 'Queens'],
        'Mogalthur': ['Manhattan', 'Brooklyn', 'Queens'],
        'Nidradavole': ['Manhattan', 'Brooklyn', 'Queens'],
        'Jangareddigudem': ['Manhattan', 'Brooklyn', 'Queens'],
        'Bhimavaram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Akividu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Tanuku': ['Manhattan', 'Brooklyn', 'Queens'],
        'Tadepalligudem': ['Manhattan', 'Brooklyn', 'Queens'],
        'Yelamanchili': ['Manhattan', 'Brooklyn', 'Queens'],
      },
      'Krishna': {
        'Avanigadda': ['Manhattan', 'Brooklyn', 'Queens'],
        'Bantumilli': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Bapulapadu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Challapalli': ['Manhattan', 'Brooklyn', 'Queens'],
        'Gannavaram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Ghantasala': ['Manhattan', 'Brooklyn', 'Queens'],
        'Gudivada': ['Manhattan', 'Brooklyn', 'Queens'],
        'Gudlavalleru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Guduru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kankipadu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Koduru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kruthivennu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Machilipatnam': ['Manhattan', 'Brooklyn', 'Queens'],
        'Mopidevi': ['Manhattan', 'Brooklyn', 'Queens'],
        'Movva': ['Manhattan', 'Brooklyn', 'Queens'],
        'Nagayalanka': ['Manhattan', 'Brooklyn', 'Queens'],
        'Nandivada': ['Manhattan', 'Brooklyn', 'Queens'],
        'Pamarru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Pamidimukkala': ['Manhattan', 'Brooklyn', 'Queens'],
        'Pedana': ['Manhattan', 'Brooklyn', 'Queens'],
        'Pedaparupudi': ['Manhattan', 'Brooklyn', 'Queens'],
        'Penamaluru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Thotlavalluru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Unguturu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Vuyyuru': ['Manhattan', 'Brooklyn', 'Queens'],
      },
      'Guntur': {
        'Guntur East': ['Manhattan', 'Brooklyn', 'Queens'],
        'Guntur West': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Medikonduru': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Pedakakani': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Pedanandipadu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Phirangipuram': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Prathipadu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Tadikonda': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Thullur': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Vatticherukuru': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Mangalagiri': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Tadepalle': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Duggirala': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Kollipara': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Chebrolu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Kakumanu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Ponnur': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Tenali': ['Los Angeles', 'San Francisco', 'San Diego'],
      },
      'Vizianagaram': {
        'VIZIANAGARAM': ['Manhattan', 'Brooklyn', 'Queens'],
        'GANTYADA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'PUSAPATIREGA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'DENKADA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'BHOGAPURAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'SRUNGAVARAPUKOTA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'JAMI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'VEPADA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'LAKKAVARAPUKOTA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'KOTHAVALASA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'NELLIMARLA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'CHEEPURUPALLI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'GARIVIDI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'GURLA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'MERAKAMUDIAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'RAJAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'VANGARA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'REGIDLAMANDALAVALASA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'SANTHAKAVITI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'BOBBILI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'RAMABHADRAPURAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'BADANGI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'THERLAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'MENTADA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'GAJAPATHINAGARAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'DATTIRAJERU': ['Los Angeles', 'San Francisco', 'San Diego'],
        'BONDAPALLI': ['Los Angeles', 'San Francisco', 'San Diego'],
      },
      'Kakinada': {
        'Gollaprolu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Pithapuram': ['Los Angeles', 'San Francisco', 'San Diego'],
        'U.Kotapalli': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Kakinada (R)': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Kakinada (U)': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Samalkota': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Karapa': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Pedapudi': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Kajuluru': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Thallarevu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Kotananduru': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Tuni': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Thondangi': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Shankhavaram': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Prathipadu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Yeleswaram': ['Los Angeles', 'San Francisco', 'San Diego'],
        'jaggampeta': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Kirlampudi': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Peddapuram': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Gandepalli': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Rowtulapudi': ['Los Angeles', 'San Francisco', 'San Diego'],
        
      },
      'Srikakulam': {
        'Srikakulam': ['Manhattan', 'Brooklyn', 'Queens'],
        'Gara': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Polaki': ['Manhattan', 'Brooklyn', 'Queens'],
        'Narasannapeta': ['Manhattan', 'Brooklyn', 'Queens'],
        'Amadalavalasa': ['Manhattan', 'Brooklyn', 'Queens'],
        'Sarubujjili': ['Manhattan', 'Brooklyn', 'Queens'],
        'Burja': ['Manhattan', 'Brooklyn', 'Queens'],
        'Ponduru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Etcherla': ['Manhattan', 'Brooklyn', 'Queens'],
        'Laveru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Ranasthalam': ['Manhattan', 'Brooklyn', 'Queens'],
        'G.Sigadam': ['Manhattan', 'Brooklyn', 'Queens'],
        'Jalumuru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Tekkali': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kotabommali': ['Manhattan', 'Brooklyn', 'Queens'],
        'Santabommali': ['Manhattan', 'Brooklyn', 'Queens'],
        'Saravakota': ['Manhattan', 'Brooklyn', 'Queens'],
        'Pathapatnam': ['Manhattan', 'Brooklyn', 'Queens'],
        'Meliaputti': ['Manhattan', 'Brooklyn', 'Queens'],
        'Hiramandalam': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kotturu': ['Manhattan', 'Brooklyn', 'Queens'],
        'L.N.Peta': ['Manhattan', 'Brooklyn', 'Queens'],
        'Nandigam': ['Manhattan', 'Brooklyn', 'Queens'],
        'Palasa': ['Manhattan', 'Brooklyn', 'Queens'],
        'Sompeta': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kavity': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kanchili': ['Manhattan', 'Brooklyn', 'Queens'],
        'Ichapuram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Vajrapukotturu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Mandasa': ['Manhattan', 'Brooklyn', 'Queens'],
        
      },
      'Prakasam': {
        'Chimakurthi': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kotha patnam': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Maddi padu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Naguluppala padu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Ongole': ['Manhattan', 'Brooklyn', 'Queens'],
        'Tanguturu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Santha Nuthalapadu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kondapi': ['Manhattan', 'Brooklyn', 'Queens'],
        'Mundlamuru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Singaraya konda': ['Manhattan', 'Brooklyn', 'Queens'],
        'Talluru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Zarugumalli': ['Manhattan', 'Brooklyn', 'Queens'],
        'Darsi': ['Manhattan', 'Brooklyn', 'Queens'],
        'DonaKonda': ['Manhattan', 'Brooklyn', 'Queens'],
        'H.M padu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kanigiri': ['Manhattan', 'Brooklyn', 'Queens'],
        'Konakana mitla': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kurichedu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Marripudi': ['Manhattan', 'Brooklyn', 'Queens'],
        'Pamuru': ['Manhattan', 'Brooklyn', 'Queens'],
        'P.C palli': ['Manhattan', 'Brooklyn', 'Queens'],
        'Podili': ['Manhattan', 'Brooklyn', 'Queens'],
        'Ponnaluru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Veligandla': ['Manhattan', 'Brooklyn', 'Queens'],
        'C.S Puram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Ardhaveedu	': ['Manhattan', 'Brooklyn', 'Queens'],
        'Bestavaripeta': ['Manhattan', 'Brooklyn', 'Queens'],
        'Cumbum': ['Manhattan', 'Brooklyn', 'Queens'],
        'Dornala': ['Manhattan', 'Brooklyn', 'Queens'],
        'Giddaluru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Komarolu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Markapuram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Peddaraveedu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Pullalacheruvu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Racherla': ['Manhattan', 'Brooklyn', 'Queens'],
        'Tripuramtakam': ['Manhattan', 'Brooklyn', 'Queens'],
        'Yerragonda palem': ['Manhattan', 'Brooklyn', 'Queens'],
        'Tarlupadu': ['Manhattan', 'Brooklyn', 'Queens'],
      },
      'Eluru': {
        'Eluru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Denduluru': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Pedavegi': ['Manhattan', 'Brooklyn', 'Queens'],
        'Pedapadu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Unguturu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Bhimadole': ['Manhattan', 'Brooklyn', 'Queens'],
        'Nidamarru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Ganapavaram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kaikaluru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Mandavalli': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kalidindi': ['Manhattan', 'Brooklyn', 'Queens'],
        'Mudinepalle': ['Manhattan', 'Brooklyn', 'Queens'],
        'Nuziveedu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Agiripalli': ['Manhattan', 'Brooklyn', 'Queens'],
        'Chatrai': ['Manhattan', 'Brooklyn', 'Queens'],
        'Musunuru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Chintalapudi': ['Manhattan', 'Brooklyn', 'Queens'],
        'Lingapalem': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kamavarapukota': ['Manhattan', 'Brooklyn', 'Queens'],
        'T. Narasapuram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Jangareddygudem': ['Manhattan', 'Brooklyn', 'Queens'],
        'Polavaram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Buttaigudem': ['Manhattan', 'Brooklyn', 'Queens'],
        'Jeelugumilli': ['Manhattan', 'Brooklyn', 'Queens'],
        'Koyyalagudem': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kukunoor': ['Manhattan', 'Brooklyn', 'Queens'],
        'Velairpad': ['Manhattan', 'Brooklyn', 'Queens'],
      },
      'Chittor': {
        '': ['Manhattan', 'Brooklyn', 'Queens'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],

      },
      'Visakhapatnam': {
        'ANANDAPURAM': ['Manhattan', 'Brooklyn', 'Queens'],
        'BHEEMUNIPATNAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'VISAKHAPATNAM(R)': ['Manhattan', 'Brooklyn', 'Queens'],
        'SEETHAMMADHARA': ['Manhattan', 'Brooklyn', 'Queens'],
        'PADMANABHAM': ['Manhattan', 'Brooklyn', 'Queens'],
        'MULAGADA': ['Manhattan', 'Brooklyn', 'Queens'],
        'MAHARANIPETA': ['Manhattan', 'Brooklyn', 'Queens'],
        'GOPALPATNAM': ['Manhattan', 'Brooklyn', 'Queens'],
        'GAJUWAKA': ['Manhattan', 'Brooklyn', 'Queens'],
        'PEDAGANTYADA': ['Manhattan', 'Brooklyn', 'Queens'],
        'PENDURTHI': ['Manhattan', 'Brooklyn', 'Queens'],
      },
      'Nellore': {
        '': ['Manhattan', 'Brooklyn', 'Queens'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        
      },
      'Bapatla': {
        'Tsundur': ['Manhattan', 'Brooklyn', 'Queens'],
        'Amruthalur': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Vemuru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kollur': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Bhattiprolu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Cherukupalle': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Nizampatnam': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Nagaram': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Repalle': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Pittalavanipalem': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Karlapalem': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Bapatla': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Chinaganjam': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Inkollu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Karamchedu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Martur': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Parchur': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Yeddanapudi': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Addanki': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Ballikurava': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Janakavarampanguluru': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Korisapadu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Santhamaguluru': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Chirala': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Vetapalem': ['Los Angeles', 'San Francisco', 'San Diego'],
      },
      'Anakapalli': {
        'Anakapalli': ['Manhattan', 'Brooklyn', 'Queens'],
        'ATCHUTAPURAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'BUTCHIAHPETA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'KASIMKOTA': ['Manhattan', 'Brooklyn', 'Queens'],
        'CHODAVARAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'DEVARAPALLI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'ELAMANCHILI': ['Manhattan', 'Brooklyn', 'Queens'],
        'K.KOTAPADU': ['Los Angeles', 'San Francisco', 'San Diego'],
        'RAMBILLI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'MUNAGAPAKA': ['Manhattan', 'Brooklyn', 'Queens'],
        'PARAWADA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'SABBAVARAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'CHEEDIKADA': ['Manhattan', 'Brooklyn', 'Queens'],
        'MADUGULA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'GOLUGONDA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'KOTAURATLA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'MAKAVARAPALEM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'NAKKAPALLI': ['Manhattan', 'Brooklyn', 'Queens'],
        'NARSIPATNAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'NATHAVARAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'PAYAKARAOPETA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'RAVIKAMATHAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'ROLUGUNTA': ['Manhattan', 'Brooklyn', 'Queens'],
        'S.RAYAVARAM': ['Los Angeles', 'San Francisco', 'San Diego'],
      },
      'Tirupati': {
        'TIRUPATI': ['Manhattan', 'Brooklyn', 'Queens'],
        'PAKALA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'TIRUPATI RURAL': ['Los Angeles', 'San Francisco', 'San Diego'],
        'CHINNAGOTTIGALLU': ['Manhattan', 'Brooklyn', 'Queens'],
        'YERRAVARIPALEM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'RAMACHANDRAPURAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'PUTUR': ['Manhattan', 'Brooklyn', 'Queens'],
        'VADAMALAPETA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'K V B PURAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'NAGALAPURAM': ['Manhattan', 'Brooklyn', 'Queens'],
        'NARAYANAVANAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'PICHATUR': ['Los Angeles', 'San Francisco', 'San Diego'],
        'RENIGUNTA': ['Manhattan', 'Brooklyn', 'Queens'],
        'SRIKALAHASTI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'THOTTAMBEDU': ['Los Angeles', 'San Francisco', 'San Diego'],
        'YERPEDU': ['Manhattan', 'Brooklyn', 'Queens'],
        'BUCHINAIDU KHANDRIGA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'SATYAVEDU': ['Los Angeles', 'San Francisco', 'San Diego'],
        'VARADAIAHPALEM': ['Manhattan', 'Brooklyn', 'Queens'],
        'OZILI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'NAIDUPET': ['Los Angeles', 'San Francisco', 'San Diego'],
        'PELLAKUR': ['Manhattan', 'Brooklyn', 'Queens'],
        'DORAVARISATRAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'SULLURUPETA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'TADA': ['Manhattan', 'Brooklyn', 'Queens'],
        'GUDUR': ['Los Angeles', 'San Francisco', 'San Diego'],
        'CHILLAKUR': ['Los Angeles', 'San Francisco', 'San Diego'],
        'KOTA': ['Manhattan', 'Brooklyn', 'Queens'],
        'VAKADU': ['Los Angeles', 'San Francisco', 'San Diego'],
        'CHITTAMUR': ['Los Angeles', 'San Francisco', 'San Diego'],
        'BALAYAPALLI': ['Manhattan', 'Brooklyn', 'Queens'],
        'VENKATAGIRI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'DAKKILI': ['Los Angeles', 'San Francisco', 'San Diego'],
        
      },
      'NTR district': {
        'A Konduru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Chandarlapadu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Gampalagudem': ['Manhattan', 'Brooklyn', 'Queens'],
        'G Konduru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Ibrahimpatnam': ['Manhattan', 'Brooklyn', 'Queens'],
        'Jaggaiahpeta': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Kanchikacherla': ['Manhattan', 'Brooklyn', 'Queens'],
        'Mylavaram': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Nandigama': ['Manhattan', 'Brooklyn', 'Queens'],
        'Penuganchiprolu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Reddigudem': ['Manhattan', 'Brooklyn', 'Queens'],
        'Tiruvuru': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Vatsavai': ['Manhattan', 'Brooklyn', 'Queens'],
        'Veerullapadu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Vijayawada Rural': ['Manhattan', 'Brooklyn', 'Queens'],
        'Vijayawada Central': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Vijayawada East ': ['Manhattan', 'Brooklyn', 'Queens'],
        'Vijayawada North	': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Vijayawada West': ['Manhattan', 'Brooklyn', 'Queens'],
        'Vissannapeta': ['Los Angeles', 'San Francisco', 'San Diego'],
       
      },
      'Alluri sitarama raju district': {
        'ANANTHAGIRI': ['Manhattan', 'Brooklyn', 'Queens'],
        'ARAKUVALLEY': ['Los Angeles', 'San Francisco', 'San Diego'],
        'CHINTHAPALLI': ['Manhattan', 'Brooklyn', 'Queens'],
        'DUMBRIGUDA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'G.K.VEEDHI': ['Manhattan', 'Brooklyn', 'Queens'],
        'G.MADUGULA': ['Los Angeles', 'San Francisco', 'San Diego'],
        'HUKUMPETA': ['Manhattan', 'Brooklyn', 'Queens'],
        'KOYYURU': ['Los Angeles', 'San Francisco', 'San Diego'],
        'MUNCHINGPUT': ['Manhattan', 'Brooklyn', 'Queens'],
        'PADERU': ['Los Angeles', 'San Francisco', 'San Diego'],
        'PEDABAYULU': ['Manhattan', 'Brooklyn', 'Queens'],
        'MAREDUMILLI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'DEVIPATNAM': ['Manhattan', 'Brooklyn', 'Queens'],
        'Y.RAMAVARAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'ADDATEEGALA': ['Manhattan', 'Brooklyn', 'Queens'],
        'GANGAVARAM': ['Los Angeles', 'San Francisco', 'San Diego'],
        'RAMPACHODAVARAM': ['Manhattan', 'Brooklyn', 'Queens'],
        'RAJAVOMMANGI': ['Los Angeles', 'San Francisco', 'San Diego'],
        'KUNAVARAM': ['Manhattan', 'Brooklyn', 'Queens'],
        'CHINTOOR': ['Los Angeles', 'San Francisco', 'San Diego'],
        'VARARAMACHANDRAPURAM': ['Manhattan', 'Brooklyn', 'Queens'],
        'NELLIPAKA': ['Los Angeles', 'San Francisco', 'San Diego'],
        
      },
      'Annamayya district': {
        'Madanapalle': ['Manhattan', 'Brooklyn', 'Queens'],
        'Nimmanapalle': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Ramasamudram': ['Manhattan', 'Brooklyn', 'Queens'],
        'Thamballapalle': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Mulakalacheruvu': ['Manhattan', 'Brooklyn', 'Queens'],
        'Peddamandyam': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Kurabalakota': ['Manhattan', 'Brooklyn', 'Queens'],
        'Peddathippasamudram': ['Los Angeles', 'San Francisco', 'San Diego'],
        'B.Kothakota': ['Manhattan', 'Brooklyn', 'Queens'],
        'Kalikiri': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Vayalpad': ['Manhattan', 'Brooklyn', 'Queens'],
        'Chitvel': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Kodur': ['Manhattan', 'Brooklyn', 'Queens'],
        'Obulavaripalli': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Tsundupalli': ['Manhattan', 'Brooklyn', 'Queens'],
        'Veeraballi': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Penagalur': ['Manhattan', 'Brooklyn', 'Queens'],
        'Pullampeta': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Nandalur': ['Manhattan', 'Brooklyn', 'Queens'],
        'Rajampet': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Rayachoti': ['Manhattan', 'Brooklyn', 'Queens'],
        'Sambepalli': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Chinnamandem': ['Manhattan', 'Brooklyn', 'Queens'],
        'Galiveedu': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Lakkireddypalli': ['Manhattan', 'Brooklyn', 'Queens'],
        'Ramapuram': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Pileru': ['Manhattan', 'Brooklyn', 'Queens'],
        'Gurramkonda': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Kalkada': ['Manhattan', 'Brooklyn', 'Queens'],
        'K V Palli': ['Los Angeles', 'San Francisco', 'San Diego'], 
      },
      'Parvathipuram manyam': {
        'Komarada': ['Manhattan', 'Brooklyn', 'Queens'],
        'Parvathipuram': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Makkuva': ['Manhattan', 'Brooklyn', 'Queens'],
        'Seethanagaram': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Balijipeta': ['Manhattan', 'Brooklyn', 'Queens'],
        'Salur': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Pachipenta': ['Manhattan', 'Brooklyn', 'Queens'],
        'Gummalakshmipuram': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Kurupam': ['Manhattan', 'Brooklyn', 'Queens'],
        'Jiyammavalasa': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Garugubilli': ['Manhattan', 'Brooklyn', 'Queens'],
        'Palakonda': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Seetampeta': ['Manhattan', 'Brooklyn', 'Queens'],
        'Bhamini': ['Los Angeles', 'San Francisco', 'San Diego'],
        'Veeraghattam': ['Manhattan', 'Brooklyn', 'Queens'],
      },
      'Komaseema': {
        '': ['Manhattan', 'Brooklyn', 'Queens'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        '': ['Los Angeles', 'San Francisco', 'San Diego'],
        
      },
  };
  
  const distSelect = document.getElementById('district');
  const mandalaSelect = document.getElementById('mandal');
  const villageSelect = document.getElementById('village');
  
  function populateCountries() {
    distSelect.innerHTML = '';
  
    const defaultOption = document.createElement('option');
    defaultOption.text = 'Select a District';
    distSelect.add(defaultOption);
  
    for (const country in data) {
      const option = document.createElement('option');
      option.value = country;
      option.text = country;
      distSelect.add(option);
    }
  
    distSelect.addEventListener('change', populateDistricts);
  }
  
  function populateDistricts() {
    const selectedCountry = distSelect.value;
  
    mandalaSelect.innerHTML = '';
  
    const defaultOption = document.createElement('option');
    defaultOption.text = 'Select a Mandal';
    mandalaSelect.add(defaultOption);
  
    for (const district in data[selectedCountry]) {
      const option = document.createElement('option');
      option.value = district;
      option.text = district;
      mandalaSelect.add(option);
    }
  
    mandalaSelect.addEventListener('change', populateMandals);
  }
  
  function populateMandals() {
    const selectedCountry = distSelect.value;
    const selectedDistrict = mandalaSelect.value;
  
    villageSelect.innerHTML = '';
  
    const defaultOption = document.createElement('option');
    defaultOption.text = 'Select a Village';
    villageSelect.add(defaultOption);
  
    const mandals = data[selectedCountry][selectedDistrict];
    for (const mandal of mandals) {
      const option = document.createElement('option');
      option.value = mandal;
      option.text = mandal;
      villageSelect.add(option);
    }
  }
  
  populateCountries();
  
  